### PR TITLE
Version for OMV3 bis

### PR DESCRIPTION
**Pull request by prbond**

### CODE REVIEW

**Comment by ryecoaaron** [comment]
Since there were conflicts in this request as well, I just merged your changes as a commit.  Can you check to make sure they are correct?  I also made a 1.x branch to hold the code for OMV 1.x and 2.x compatibility since we typically keep the current OMV version code in the master branch where I merged your changes.

**Comment by prbond** [comment]
Yes i think all are ok, but maybe create branch 2.X instead 1.X and rename master-omv to 3.X ?

**Comment by ryecoaaron** [comment]
I named it 1.x since the control file said it still worked with OMV 1.x.  You can name the branches whatever you want.  I was just suggesting what we do with the other plugins.  You have permissions to create branches, right?

**Comment by prbond** [comment]
I begin with OMV 2.X.
Yes i have permissions but i need your advice before making a stupidity.

**Comment by ryecoaaron** [comment]
I changed it to 2.x.  I'm sure you won't do anything stupid :)

**Pull request closed without merging**
